"""
MediScan AI - Prescription OCR + Clean Format
"""

import streamlit as st
from PIL import Image
import pytesseract
import re
from difflib import SequenceMatcher
from database import MEDICINES, get_all_medicine_names


@st.cache_data(show_spinner=False)
def extract_text_from_image(image_bytes):
    try:
        img = Image.open(image_bytes)
        img = img.convert("L")
        text = pytesseract.image_to_string(img)
        return text
    except Exception as e:
        return f"OCR_ERROR: {str(e)}"


def _similarity(a: str, b: str) -> float:
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()


def extract_medicine_names(text: str):
    """Extract medicine names using fuzzy matching + confidence scoring."""
    if not text or "OCR_ERROR" in text:
        return []

    text_lower = text.lower()
    words = re.findall(r'\b[a-zA-Z]{4,}\b', text)
    found = {}

    for med in MEDICINES:
        med_name = med["name"].lower()
        generic = med["generic"].lower().split()[0]

        # Exact match
        if med_name in text_lower or generic in text_lower:
            found[med["name"]] = {
                "medicine": med["name"],
                "generic": med["generic"],
                "confidence": 0.95,
                "matched_text": med["name"] if med_name in text_lower else med["generic"]
            }
            continue

        # Fuzzy match — best word similarity
        best_score = 0
        best_word = ""
        for word in words:
            score = max(_similarity(word, med["name"]), _similarity(word, med["generic"].split()[0]))
            if score > best_score:
                best_score = score
                best_word = word

        if best_score >= 0.75:
            found[med["name"]] = {
                "medicine": med["name"],
                "generic": med["generic"],
                "confidence": round(best_score, 2),
                "matched_text": best_word
            }

    return list(found.values())


def suggest_alternatives(word: str, top_k=3):
    """Suggest similar medicine names."""
    scores = []
    for med in MEDICINES:
        sim = max(
            _similarity(word, med["name"]),
            _similarity(word, med["generic"].split()[0])
        )
        scores.append((med["name"], round(sim, 2)))
    scores.sort(key=lambda x: -x[1])
    return scores[:top_k]


def format_prescription(medicines_found: list, raw_text: str) -> str:
    """Format extracted medicines into clean readable text."""
    lines = []
    lines.append("=" * 50)
    lines.append("       MEDISCAN AI — PRESCRIPTION REPORT")
    lines.append("=" * 50)
    lines.append("")
    lines.append(f"Total Medicines Detected: {len(medicines_found)}")
    lines.append("")
    lines.append("-" * 50)
    lines.append("MEDICINES:")
    lines.append("-" * 50)

    if not medicines_found:
        lines.append("  No medicines detected. Prescription may be unclear.")
    else:
        for i, m in enumerate(medicines_found, 1):
            lines.append(f"\n{i}. {m['medicine']}")
            lines.append(f"   Generic:    {m['generic']}")
            lines.append(f"   Confidence: {m['confidence'] * 100:.0f}%")
            lines.append(f"   Matched:    {m['matched_text']}")

    lines.append("")
    lines.append("-" * 50)
    lines.append("RAW OCR TEXT:")
    lines.append("-" * 50)
    lines.append(raw_text if raw_text else "N/A")
    lines.append("")
    lines.append("=" * 50)
    lines.append("Generated by MediScan AI — Educational use only")
    lines.append("Consult a licensed doctor before taking any medicine.")
    lines.append("=" * 50)

    return "\n".join(lines)
