"""
MediScan AI - Prescription OCR (Improved)
ONLY extracts medicine names — filters out names, dates, addresses.
"""

import streamlit as st
from PIL import Image
import pytesseract
import re
from difflib import SequenceMatcher
from database import MEDICINES


# Words that should NEVER be treated as medicines
STOP_WORDS = {
    "prescription", "doctor", "name", "patient", "address", "date",
    "clinic", "hospital", "medical", "rx", "age", "sex", "male",
    "female", "signature", "sign", "consultant", "dr", "street",
    "road", "city", "phone", "mobile", "email", "registration",
    "diagnosis", "complaint", "history", "examination", "advice",
    "follow", "review", "your", "take", "tablet", "capsule", "daily",
    "times", "day", "morning", "evening", "night", "after", "before",
    "meal", "food", "needed", "pain", "one", "two", "three", "four",
    "five", "mg", "ml", "mcg", "gm", "kg", "us", "lb", "the", "and",
    "for", "with", "from", "this", "that", "have", "has", "been",
    "will", "would", "could", "should", "may", "might", "must",
    "el", "springfield", "doe", "john", "smith", "your", "clinic",
}


@st.cache_data(show_spinner=False)
def extract_text_from_image(image_bytes):
    try:
        img = Image.open(image_bytes)
        img = img.convert("L")
        text = pytesseract.image_to_string(img)
        return text
    except Exception as e:
        return f"OCR_ERROR: {str(e)}"


def _similarity(a: str, b: str) -> float:
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()


def extract_medicine_names(text: str):
    """
    Extract ONLY medicine names from OCR text.
    Filters out common non-medicine words (names, dates, addresses).
    """
    if not text or "OCR_ERROR" in text:
        return []

    found = {}

    # Get all valid medicine names + generics
    valid_meds = []
    for med in MEDICINES:
        valid_meds.append((med["name"].lower(), med))
        # Also add generic first word
        generic_first = med["generic"].lower().split()[0]
        if len(generic_first) >= 4:
            valid_meds.append((generic_first, med))

    # Tokenize text into words (remove digits, punctuation)
    words = re.findall(r'\b[a-zA-Z]{4,}\b', text)

    for word in words:
        word_lower = word.lower()

        # Skip stop words
        if word_lower in STOP_WORDS:
            continue

        # Match against valid medicines
        for med_key, med in valid_meds:
            if med["name"] in found:
                continue

            # Exact match
            if word_lower == med_key:
                found[med["name"]] = {
                    "medicine": med["name"],
                    "generic": med["generic"],
                    "confidence": 0.95,
                }
                break

            # Fuzzy match (high threshold to avoid false positives)
            score = _similarity(word_lower, med_key)
            if score >= 0.85:
                found[med["name"]] = {
                    "medicine": med["name"],
                    "generic": med["generic"],
                    "confidence": round(score, 2),
                }
                break

    return list(found.values())


def format_prescription(medicines_found: list) -> str:
    """Format extracted medicines into clean readable text."""
    lines = []
    lines.append("=" * 55)
    lines.append("       MEDISCAN AI — PRESCRIPTION REPORT")
    lines.append("=" * 55)
    lines.append("")
    lines.append(f"Medicines Detected: {len(medicines_found)}")
    lines.append("")
    lines.append("-" * 55)

    if not medicines_found:
        lines.append("  No medicines detected.")
        lines.append("  Prescription may be unclear.")
    else:
        for i, m in enumerate(medicines_found, 1):
            lines.append("")
            lines.append(f"  {i}. {m['medicine'].upper()}")
            lines.append(f"     Generic:    {m['generic']}")
            lines.append(f"     Confidence: {m['confidence'] * 100:.0f}%")

    lines.append("")
    lines.append("-" * 55)
    lines.append("Generated by MediScan AI")
    lines.append("Educational purposes only.")
    lines.append("Consult a licensed doctor before use.")
    lines.append("=" * 55)

    return "\n".join(lines)
